blank_issues_enabled: false
contact_links:
  - name: Read Our Contribution Guidelines
    url: https://github.com/atodd-extron/iis-logs/CONTRIBUTING.md
    about: Please review this before opening an issue.
issue_templates:
  - name: Standard Issue
    description: Use this template for general tasks, refactoring, docs, or planning.
    file: standard_issue.md
  - name: Feature Request
    description: Request a new feature or capability for the project.
    file: feature_request.md
  - name: Bug Report
    description: Report a reproducible issue or unexpected behavior.
    file: bug_report.md
